### ISSUE TITLE
Water sensivitivity check doesn't work

### ISSUE THREAD

**Issue by kakashi1464** [ThinkingStudios/RyoamicLights#10]
**Describe the bug**
Water sensivitivity check doesn't work

**To Reproduce**
1. Install Ryoamic Lights with its dependencies 
1. Go to 'Ryoamic Lights config'
2. Enable 'Water sensivitivity check'
3. Load world 

**Expected behavior**
I expected that dynamic lighting would not work in water

**Screenshots**
![2023-11-21_15 06 01](https://github.com/ThinkingStudios/LambDynamicLights-Forge/assets/126709049/e200420f-3776-4526-a26d-879a24ebd2fe)
![image](https://github.com/ThinkingStudios/LambDynamicLights-Forge/assets/126709049/435fbae2-0f96-4fc6-8333-b82c204e2be8)

**Desktop (please complete the following information):**
- OS: [Windows 10]
- Minecraft [1.20.1]
- Forge [47.1.3]
- Mods [Ryoamic lights, Architectury API, Obsidian UI]
- Version [0.1.5+1.20.1]
- Branch [1.20-forge]

**Comment by TexBlock** [comment]
fixed in 0.1.6
