### ISSUE TITLE
Datagen doesn't work with mod installed

### ISSUE THREAD

**Issue by thomasglasser** [ThinkingStudios/RyoamicLights#12]
**Describe the bug**
When running forge datagen, it crashes because `Minecraft.getInstance()` returns null.

**To Reproduce**
1. Install mod
2. Run datagen

**Expected behavior**
The mod wouldn't run any logic during datagen

**Additional context**
This should be fixed by checking if it returns null during client initialization

**Comment by TexBlock** [comment]
log?

**Comment by thomasglasser** [comment]
[latest.log](https://github.com/ThinkingStudios/LambDynamicLights-Forge/files/13720924/latest.log)

**Comment by thomasglasser** [comment]
The arch port removed this check and this issue is back
