### ISSUE TITLE
Crash with mods

### ISSUE THREAD

**Issue by Darklight-007** [ThinkingStudios/RyoamicLights#15]
**Describe the bug**
crash

**To Reproduce**
idk

**Desktop (please complete the following information):**
 - OS: [Windows
 - Minecraft 1.20.1
 

**Additional context**
logs:-https://mclo.gs/Egy16vS

**Comment by TexBlock** [comment]
You can roll back the ObsidianUI version to 0.1.2 and I'll fix this afterward

**Comment by TexBlock** [comment]
fixed in 0.2.0
