### ISSUE TITLE
Crash when i opened settings?

### ISSUE THREAD

**Issue by Killercrab432** [ThinkingStudios/RyoamicLights#17]
**Describe the bug**
Game just crashed twice when i open settings, im assuming this mod is related as it only happened after i added it

**To Reproduce**
1. Go to my modpack
2. Click on options
4. game crashes

**Expected behavior**
Game to not crash

**Screenshots**
https://pastebin.com/5bjU3jTy

 - OS: Windows
 - Minecraft 1.20.1
 - Fabric Loader version 0.15.7
 - Mods Too many to list here

**Additional context**
Im aware this is probably just a random mod incompatibility, but just posting here in the hopes you have an idea on what could be causing it or what type of mods i could investigate that could be causing the issue

**Comment by TexBlock** [comment]
fixed in 0.2.1
