### ISSUE TITLE
Incompatible with SimplySwords

### ISSUE THREAD

**Issue by Mouy07** [ThinkingStudios/RyoamicLights#22]
**Describe the bug**
The game will not launch if SimplySwords is installed with Ryoamic Lights.

**To Reproduce**
1. Install Ryoamic Lights and SimplySwords with dependencies
2. Launch game
3. Fails to launch

**Desktop (please complete the following information):**
 - OS: Windows
 - Minecraft: 1.20.1
 - Fabric Loader version: 0.15.10
 - Mods: Ryoamic Lights 0.2.3, SimplySwords 1.55.0

**Logs**
https://mclo.gs/eaogws5

**Comment by TexBlock** [comment]
fixed
