### ISSUE TITLE
RyoamicLights doesn't emit light with Radiant Gear + Trinkets.

### ISSUE THREAD

**Issue by bigmanmad** [ThinkingStudios/RyoamicLights#23]
**Describe the bug**
Radiant Gear supposedly adds the ability to give off dynamic lighting with torches in trinket slots, with RyoamicLights listed as working, but nothing happens. Perhaps I did something wrong but works fine with LambDynamicLights.

**To Reproduce**
1. Install RyoamicLights, Radiant Gear, Trinkets and any other dependencies you may need.
2. Add [this datapack](https://www.dropbox.com/scl/fi/14ldxdih6jwbo6t2ct4zx/Trinket-Lights.zip?rlkey=2pht4z4ov4xrjdw80oz51chrc&st=9lh8qwq2&dl=1) to allow torches and lanterns to be placed on the belt.
3. Go into a world and place a torch on your hip in the dark.
4. No light is emitted.

**Expected behavior**
You are expected to give off light as if it is in your offhand but nothing happens, works fine with LambDynamicLights but not RyoamicLights/

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Minecraft 1.20.1
 - Fabric Loader version 0.15.11
 - Mods: RyoamicLights, Radiant Gear, Trinkets
 - Version 0.2.1+mc1.20.1
 - Branch 1.20.1

**Additional context**
Nothing else to note.

**Comment by TexBlock** [comment]
@bigmanmad Radiant Gear is only compatible with RyoamicLights on the (Neo)Forge side.
