### ISSUE TITLE
`0.2.5+mc1.20.6` crashes in NeoForge `20.6.70-beta`

### ISSUE THREAD

**Issue by 3gf8jv4dv** [ThinkingStudios/RyoamicLights#24]
**Describe the bug**
Game shows error interface. :(

**To Reproduce**
1. Install NeoForge, RyoamicLights and their dependencies
2. Start the game
3. Game shows error interface

**Expected behavior**
Start the game normally.

**Screenshots**
_None_

**Desktop (please complete the following information):**
 - OS: Microsoft Windows
 - Minecraft: 1.20.6
 - NeoForge version: 20.6.70-beta
 - Mods: `ryoamiclights 0.2.5+mc1.20.6`, `obsidianui 0.2.4+mc1.20.6`
 - Version: 0.2.5
 - Branch: mc1.20.6

**Additional context**
Log _(Deleted)_

**Comment by TexBlock** [comment]
fixed in 0.2.6
