### ISSUE TITLE
[Incompatible] Incompatible with Ars Nouveau

### ISSUE THREAD

**Issue by JohnM514** [ThinkingStudios/RyoamicLights#3]
When trying to load a world it crashes

1. Open Minecraft
2. Click on 'Singleplayer'
3. Select a world
4. Load the world
5. It will state that its joining the world, the loading the terrain and right before crashing to desktop it would state that its saving the world

**Expected behavior**
It should load the world.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Minecraft 1.19.2
 - Forge Loader 43.2.3
 - Mods:
  [✔] 3dskinlayers-forge-1.5.2-mc1.19.1
  [✔] AdChimneys-1.19.2-9.1.13.0-build.0988
  [✔] additional_lights-1.19-2.1.6
  [✔] AdvancementPlaques-1.19.2-1.4.7
  [✔] AmbientEnvironment-forge-1.19.2-8.0+3
  [✔] AmbientSounds_FORGE_v5.2.13_mc1.19.2
  [✔] aquamirae-6.API15
  [✔] architectury-6.5.85-forge
  [✔] areas-1.19.2-5.0
  [✔] ars_nouveau-1.19.2-3.18.0
  [✔] arsarmiger-1.19.2-1.4.0
  [✔] astikorcarts-1.19.2-1.1.2
  [✔] auditory-0.0.5-1.19.2
  [✔] autohud-4.3+1.19.2-forge
  [✔] AutoRegLib-1.8.2-55
  [✔] badpackets-forge-0.2.2
  [✔] balm-forge-1.19.2-4.6.0
  [✔] BetterAnimationsCollection-v4.0.5-1.19.2-Forge
  [✔] betterdays-1.19.2-3.1.0.3-FORGE
  [✔] BetterF3-4.0.0-Forge-1.19.2
  [✔] BetterModsButton-v4.2.4-1.19.2-Forge
  [✔] blockui-1.19.2-0.0.92-ALPHA
  [✔] blueprint-1.19.2-6.2.0
  [✔] Bookshelf-Forge-1.19.2-16.3.20
  [✔] caelus-forge-1.19.2-3.0.0.6
  [✔] cameraoverhaul-1.0-1.19.2
  [✔] canary-mc1.19.2-0.2.8
  [✔] carryon-forge-1.19.2-2.1.1.21
  [✔] catalogue-1.7.0-1.19.2
  [✔] choicetheorems-overhauled-village-friends-and-foes-add-on-1.1
  [✔] choicetheorems-overhauled-village-incubation-add-on-1.0
  [✔] cloth-config-8.3.103-forge
  [✔] Clumps-forge-1.19.2-9.0.0+14
  [✔] CNB-1.19-1.5.2
  [✔] collective-1.19.2-6.66
  [✔] configured-2.1.1-1.19.2
  [✔] connectedness-2.0.1a
  [✔] Continents_1.20.2_v1.1.3
  [✔] Craftable-Saddles-[1.19]-1.11
  [✔] CreativeCore_FORGE_v2.9.4_mc1.19.2
  [✔] ctov-3.2.5
  [✔] ctov-farmers-delight-compat-1.2
  [✔] CullLessLeaves-Reforged-1.0.5
  [✔] curios-forge-1.19.2-5.1.4.1
  [✔] denseores-1.19.2-1.2.1
  [✔] domum_ornamentum-1.19-1.0.132-BETA-universal
  [✔] dropz-forge-2.2.0+1.19.2
  [✔] dynamic_asset_generator-forge-1.19.2-1.2.0
  [✔] dynamicvillagertrades-1.2.2-forge
  [✔] eatinganimation-1.19-3.2.0
  [✔] effective_fg-1.3.4
  [✔] elytraslot-forge-6.1.1+1.19.2
  [✔] embeddium-0.1.10+mc1.19.2
  [✔] EnchantingInfuser-v4.2.2-1.19.2-Forge
  [✔] EnchantmentDescriptions-Forge-1.19.2-13.0.14
  [✔] endrem_forge-5.2.1-R-1.19.X
  [✔] entity_model_features_forge_1.19.2-1.0.2
  [✔] entity_texture_features_forge_1.19.2-4.5.1
  [✔] entityculling-forge-1.6.1-mc1.19.2
  [✔] everycomp-1.19.2-2.5.5
  [✔] excavated_variants-forge-1.19.2-1.0.3
  [✔] Fallingleaves-1.19.1-1.3.1
  [✔] fantasyfurniture-1.19.2-6.7.0
  [✔] FarmersDelight-1.19.2-1.2.3
  [✔] Fastload-Reforged-mc1.19.2-3.4.0
  [✔] ferritecore-5.0.3-forge
  [✔] ForgeEndertech-1.19.2-10.0.6.1-build.0897
  [✔] friendsandfoes-beekeeperhut-forge-mc1.19.2-1.2.0
  [✔] friendsandfoes-flowerymooblooms-forge-mc1.19.2-1.0.0
  [✔] friendsandfoes-forge-mc1.19.2-1.8.8
  [✔] geckolib-forge-1.19-3.1.40
  [✔] gravestone-1.19.2-1.0.1
  [✔] guardvillagers-1.19.2-1.5.7
  [✔] handcrafted-forge-1.19.2-2.0.6
  [✔] HorseExpert-v4.0.0-1.19.2-Forge
  [✔] horsestandstill-1.19-1.0.3
  [✔] horsestonks-forge-1.17+-1.0.1
  [✔] Iceberg-1.19.2-forge-1.1.4
  [✔] ImmediatelyFast-1.2.5+1.19.2
  [✔] immersivesnow-1.19.2-1.2.0
  [✔] incubation-1.19-3.0.0
  [✔] inventorysorter-22.0.0
  [✔] Jewelry-1.2.10
  [✔] lazydfu-1.19-1.0.2
  [✔] lightspeed-1.19.2-1.0.5
  [✔] Log-Begone-Forge-1.19-1.0.6
  [✔] MagnumTorch-v4.2.3-1.19.2-Forge
  [✔] mcw-paths-1.0.3forge-mc1.19.2
  [✔] memoryleakfix-forge-1.17+-1.1.2
  [✔] MerchantMarkers-1.19.2-forge-1.3.1
  [✔] minecolonies-1.19.2-1.1.184-BETA
  [✔] modernfix-forge-5.7.4+mc1.19.2
  [✔] moonlight-1.19.2-2.2.46-forge
  [✔] MouseTweaks-forge-mc1.19-2.23
  [✔] mutil-1.19.2-5.1.0
  [✔] NaturalProgression-1.19.2-2.3.5
  [✔] NaturesCompass-1.19.2-1.10.0-forge
  [✔] notenoughanimations-forge-1.6.2-mc1.19.2
  [✔] obscure_api-15
  [✔] obsidianui-0.1.3+1.19.2
  [✔] oculus-mc1.19.2-1.6.9
  [✔] Patchouli-1.19.2-77
  [✔] pluto-mc1.19.2-0.0.9
  [✔] polymorph-forge-0.46.4+1.19.2
  [✔] PresenceFootsteps-1.19.2-1.6.4.1-forge
  [✔] PuzzlesLib-v4.4.3-1.19.2-Forge
  [✔] Quark-3.4-409
  [✔] randomvillagenames-1.19.2-3.2
  [✔] rayon-forge-1.7.1+1.19.2
  [✔] realisticbees-1.19.2-3.3
  [✔] reasonable-sorting-forge-2.1.0-mc1.19.2
  [✔] reforgium-1.0.12a
  [✔] resourcefullib-forge-1.19.2-1.1.24
  [✔] responsiveshields-2.2
  [✔] Ryoamiclights-0.1.1+1.19.2
  [✔] saturn-mc1.19.2-0.0.4
  [✔] SereneSeasons-1.19.2-8.1.0.24
  [✔] SkyVillages-1.0.1-1.19-forge-release
  [✔] sophisticatedbackpacks-1.19.2-3.18.58.907
  [✔] sophisticatedcore-1.19.2-0.5.87.417
  [✔] soundphysics-forge-1.19.2-1.2.1
  [✔] spiderstpo-1.19.2-2.0.4
  [✔] starlight-1.1.1+forge.cf5b10b
  [✔] structurize-1.19.2-1.0.643-RELEASE
  [✔] supplementaries-1.19.2-2.3.24
  [✔] tectonic-mod-mc1.19.2-v2.1.1
  [✔] tetra-1.19.2-5.5.1
  [✔] tetrasdelight-1.19.2-1
  [✔] textrues_embeddium_options-0.1.1+mc1.19.2
  [✔] TradingPost-v4.2.0-1.19.2-Forge
  [✔] TravelersTitles-1.19.2-Forge-3.1.2
  [✔] TreeChop-1.19.2-forge-0.18.4
  [✔] TreePlant-1.19.1-0.3.1
  [✔] twigs-forge-1.19.2-3.0.1
  [✔] UniversalEnchants-v4.2.15-1.19.2-Forge
  [✔] Villager+Comfort-1.19.2-1.0.0
  [✔] villagernames-1.19.2-5.2
  [✔] villagespawnpoint-1.19.2-4.0
  [✔] visuality-forge-2.0.2
  [✔] VisualWorkbench-v4.2.4-1.19.2-Forge
  [✔] waystones-forge-1.19.2-11.4.1
  [✔] wthit-forge-5.19.0
  [✔] yeetusexperimentus-1.0.1-build.2+mc1.19.1
  [✔] YungsApi-1.19.2-Forge-3.8.9
  [✔] YungsBetterDesertTemples-1.19.2-Forge-2.2.2
  [✔] YungsBetterDungeons-1.19.2-Forge-3.2.2
  [✔] YungsBetterMineshafts-1.19.2-Forge-3.2.0
  [✔] YungsBetterOceanMonuments-1.19.2-Forge-2.1.1
  [✔] YungsBetterStrongholds-1.19.2-Forge-3.2.0
  [✔] YungsBridges-1.19.2-Forge-3.1.0
 - Version 0.1.1 
 - Branch mc1.19.2

**Additional context**
[crash-2023-09-28_08.53.43-client.txt](https://github.com/ThinkingStudios/LambDynamicLights-Forge/files/12750954/crash-2023-09-28_08.53.43-client.txt)

**Comment by JohnM514** [comment]
After doing additional testing it seems that there is a compatibility issue with Ars Nouveau

**Comment by TexBlock** [comment]
> After doing additional testing it seems that there is a compatibility issue with Ars Nouveau


Yes, from the code it looks like Ars Nouveau has LambDynamicLights built in?

**Comment by DxsSucuk** [comment]
Does this mean Ars Nouveau already contains DynamicLights? So if someone uses Ars Nouveau they dont need to use the DynamicLights mod?

**Comment by TexBlock** [comment]
> Does this mean Ars Nouveau already contains DynamicLights? So if someone uses Ars Nouveau they dont need to use the DynamicLights mod?

Yes

**Comment by DxsSucuk** [comment]
Well while testing not too long ago, it looks like the light does not work on torches and such? Maybe only on the spell particals?

**Comment by DxsSucuk** [comment]
Nvm, figured out its completly disabled by default and needs to be enabled via the config.

**Comment by TexBlock** [comment]
I think the current solution is either AN removing the code about LDL or not installing RDL.

**Comment by JohnM514** [comment]
It makes sense, thanks , btw searching for a replacement for RDL to use with Ars Nouveau (I did not know we could just enable Ars Nouveau DL) I found Lucent which works with Ars Nouveau

**Comment by TexBlock** [comment]
i will fix in `NEXT VERSION`

**Comment by UndarkAido** [comment]
If the fix was meant to be in `0.1.3+1.20.1` it doesn't seem like it worked. Not sure of the timeline, GitHub just very helpfully shows everything as "last week".

**Comment by TexBlock** [comment]
> If the fix was meant to be in `0.1.3+1.20.1` it doesn't seem like it worked. Not sure of the timeline, GitHub just very helpfully shows everything as "last week".

AN's dynamic lights really don't work with RyoamicLights, one of the dynamic lights must be turned off for the other to take effect.

**Comment by TexBlock** [comment]
fixed in `0.1.5+1.20.1`/`0.1.4+1.19.4`/`0.1.4+1.19.3`/`0.1.4+1.19.2`/`0.1.4+1.18.2`/`0.1.5+1.16.5` again
