### ISSUE TITLE
Game doesn't launch with this mod

### ISSUE THREAD

**Issue by thebashforkbomber** [ThinkingStudios/RyoamicLights#34]
# Describe the bug
game does not launch. simple

# To Reproduce
1. Start minecraft
2. Wait for mod initialize
3. See error

# Expected Behaviour
Game launching

# Screenshots
[Mod list](https://imageserver.pw/raw/pj50WN3Q.png?key=VupggJWAt8IF1e3H1TO8AnwVvAkdV0BS)

# Desktop
 - OS: MS Windows 10
 - Minecraft 1.21
 - Fabric Loader version 0.15.11
 - Mods: Too lazy to type out, see screenshots.
 - Version 0.2.8+mc1.21
 - Branch 1.21.x-architectury

# Additional Context
It used to work, now it doesn't.
Mod list: essential-container is the Essential mod.

**Comment by thebashforkbomber** [comment]
I've also pasted a crash report on paste.ee, see here: https://paste.ee/p/S2Gks

**Comment by TexBlock** [comment]
Night Config issue, i will fix

**Comment by thebashforkbomber** [comment]
Recent patch didn't help, https://paste.ee/p/GsLq6

**Comment by thebashforkbomber** [comment]
UPD: After retrying it works?!?! I guess...

**Comment by thebashforkbomber** [comment]
Ehh, seems to work fine.
