### ISSUE TITLE
RyoamicLights crashing game on world load

### ISSUE THREAD

**Issue by LegitGamer1017** [ThinkingStudios/RyoamicLights#4]
**Describe the bug**
When I try to create a world in my modded playthrough, the game begins to load the world. RIght when it's finished loading the world, it crashes. Looking through the log, it seems like some error about dynamic lights is crashing the world. 

**To Reproduce**
1. Create a New World
2. Wait for world to load
3. See error

**Expected behavior**
The world should load normally, and I should be able to walk around and play the world normally. 

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 
 - Minecraft 1.20.1
 - NeoForge 47.1.79
 - Mods
 
 3dskinlayers-forge-1.5.4-mc1.20.1.jar
AdditionalEnchantedMiner-1.20.1-1201.0.17.jar
AdFinders-1.20.1-9.1.1.0-build.0270.jar
AdLods-1.20.1-8.1.0.0-build.0142.jar
AE2-Things-1.2.1.jar
ae2wtlib-15.1.0-forge.jar
AEAdditions-1.20.1-5.0.2.jar
aeroblender-1.20.1-1.0.1-neoforge.jar
aether-1.20.1-1.0.0-beta.1.3-neoforge.jar
aether-redux-1.2-1.20.1-neoforge.jar
aether_enhanced_extinguishing-1.20.1-1.0.0-neoforge.jar
alexsmobs-1.22.6.jar
almostunified-forge-1.20.1-0.7.0.jar
alternate_current-mc1.20-1.7.0.jar
AnimaticaReforged-1.20.1-0.0.2.jar
Apotheosis-1.20.1-7.0.5.jar
ApothicAttributes-1.20.1-1.1.4.jar
appliedenergistics2-forge-15.0.13.jar
aquamirae-6.API15.jar
architectury-9.1.12-forge.jar
armorpointspp-forge-1.20-3.1.1.jar
arseng-1.1.2.jar
ars_instrumentum-1.20.1-4.0.0.jar
ars_nouveau-1.20.1-4.7.2-all.jar
artifacts-forge-9.1.0.jar
ash_api-forge-3.0.2+1.20.1.jar
AttributeFix-Forge-1.20.1-21.0.2.jar
BadMobs-1.20.1-19.0.1.jar
balm-forge-1.20.1-7.1.4.jar
BarteringStation-v8.0.0-1.20.1-Forge.jar
BedBenefits-Forge-1.20.1-13.0.2.jar
BetterAdvancements-1.20.1-0.3.2.161.jar
betterfpsdist-1.20.1-3.9.jar
better_certus_quartz-1.20.1-1.0.6.jar
better_silicon-1.20.1-1.0.10.jar
biomemusic-1.20.1-2.2.jar
BiomesOPlenty-1.20.1-18.0.0.598.jar
blockui-1.20.1-0.0.94-ALPHA.jar
blossom-blade-1.0.jar
blue_skies-1.20.1-1.3.29.jar
Boat-Item-View-Forge-1.20.1-0.0.5.jar
BoatBreakFix-Universal-1.0.2.jar
Bookshelf-Forge-1.20.1-20.0.5.jar
Bountiful-6.0.3+1.20.1-forge.jar
bygonenether-1.3.2-1.20.x.jar
cabletiers-1.20.1-1.1.jar
caelus-forge-3.1.0+1.20.jar
canary-mc1.20.1-0.2.7.jar
car-1.20.1-1.0.8.jar
castle_dungeons-4.0.0-1.20-forge.jar
Chargers-1.20-6.0.0.23.jar
charginggadgets-1.11.0.jar
charmofundying-forge-6.4.2+1.20.1.jar
chefs-delight-1.0.3-forge-1.20.1.jar
Chunk+Pregenerator-1.20-4.2.3.jar
chunkloaders-1.2.8-forge-mc1.20.1.jar
citadel-2.4.5-1.20.1.jar
clientcrafting-1.20.1-1.7.jar
cloth-config-11.1.106-forge.jar
Cobblemon-forge-1.4.0+1.20.1.jar
cobblemonintegrations-1.20.1-1.0.0.jar
collective-1.20.1-6.66.jar
ColossalChests-1.20.1-1.8.4.jar
comforts-forge-6.3.3+1.20.1.jar
connectivity-1.20.1-4.6.jar
controllable-forge-1.20.1-0.20.3.jar
Controlling-forge-1.20.1-12.0.2.jar
corail_woodcutter-1.20.1-3.0.3.jar
CorgiLib-forge-1.20.1-4.0.0.4.jar
corpse-1.20.1-1.0.5.jar
CrabbersDelight-1.20.1-1.1.2.jar
CreativeCore_FORGE_v2.11.5_mc1.20.1.jar
creativecrafter-1.20.1-1.0.jar
ctov-3.3.5a.jar
Cucumber-1.20.1-7.0.3.jar
cuisinedelight-1.1.10.jar
cupboard-1.20.1-2.1.jar
curios-forge-5.3.5+1.20.1.jar
curious_armor_stands-1.20-5.0.1.jar
CyclopsCore-1.20.1-1.18.11.jar
dankstorage-1.20.1-1.1.jar
deathbackup-1.20.1-3.0.jar
Decorative+Blocks-forge-1.20.1-4.0.2.jar
deeperdarker-forge-1.20.1-1.2.0.jar
deep_aether-1.20.1-1.0.10.jar
does_potato_tick-1.20.1-3.6.3.jar
domum_ornamentum-1.20-1.0.136-BETA-universal.jar
doubledoors-1.20.1-5.0.jar
dragonmounts-1.20.1-1.1.5.b3.jar
DrawersTooltip-1.20.1-forge-8.0.0.jar
Dungeon+Crawl-1.20.1-2.3.14.jar
dungeons-and-taverns-3.0.3+[Forge].jar
DungeonsArise-1.20.1-2.1.57-release.jar
EasierSleeping-1.20.1-2.1.3.jar
EdivadLib-1.20.1-2.0.1.jar
elytraslot-forge-6.3.0+1.20.1.jar
embeddium-0.2.1+mc1.20.1.jar
EnchantmentDescriptions-Forge-1.20.1-17.0.8.jar
EndlessBiomes+1.4.2s+-+1.20.1.jar
ends_delight-1.20.1-1.0.1.jar
Enhanced_Celestials-forge-1.20.1-5.0.0.2.jar
entityculling-forge-1.6.2-mc1.20.1.jar
entity_texture_features_forge_1.20-4.5.1.jar
EuphoriaPatcher-0.1.1-forge.jar
everycomp-1.20-2.6.7.jar
Exchangers-1.20.1-3.5.1.jar
experienceobelisk-v1.4.8-1.20.1.jar
explorations-forge-1.20.1-1.5.2.jar
ExplorersCompass-1.20.1-1.3.3-forge.jar
explorify-v1.3.0-mc1.20u1.20.1.jar
ExtendedAE-1.20-0.1.15-forge.jar
ExtraDisks-1.20.1-3.0.0.jar
ExtraStorage-1.20.1-4.0.3.jar
ExtremeReactors2-1.20.1-2.0.74.jar
Fallingleaves-1.20.1-2.1.0.jar
FallingTree-1.20.1-5.0.0b1.jar
FarmersDelight-1.20.1-1.2.3.jar
farmingutils-1.20.1-0.1.10.jar
farsight-1.20.1-3.5.jar
fastpaintings-1.20-1.2.0.jar
ferritecore-6.0.0-forge.jar
flib-1.20.1-0.0.11.jar
FluidDrawersLegacy-1.20.1-forge-4.1.3-release.jar
FluxNetworks-1.20.1-7.2.0.14.jar
forgeautofish-6.0.0-1.20.1.jar
ForgeConfigScreens-v8.0.2-1.20.1-Forge.jar
ForgeEndertech-1.20.1-11.1.0.0-build.0142.jar
framework-forge-1.20.1-0.6.16.jar
friendsandfoes-forge-mc1.20.1-1.9.7.jar
From-The-Fog-1.20-v1.9.2-Forge-Fabric.jar
ftb-essentials-forge-2001.2.1.jar
ftb-library-forge-2001.1.3.jar
ftb-quests-forge-2001.1.6.jar
ftb-teams-forge-2001.1.4.jar
ftb-ultimine-forge-2001.1.2.jar
gardens-of-the-dead-forge-4.0.1.jar
geophilic-v2.0.0-mc1.20u1.20.1.jar
globalxp-1.20-1.10.3.jar
goblintraders-forge-1.20.1-1.9.2.jar
gpumemleakfix-1.20.1-1.6.jar
guardvillagers-1.20-1.6.2.jar
GunpowderLib-1.20.2-2.2.1.jar
handcrafted-forge-1.20.1-3.0.1.jar
hearths-v1.0.0-mc1.20u1.20.1.jar
Highlighter-1.20.1-forge-1.1.7.jar
hole_filler_mod-1.2.8_mc-1.20.1_forge.jar
HostileNeuralNetworks-1.20.1-5.1.3.jar
Iceberg-1.20.1-forge-1.1.15.jar
IllagerInvasion-v8.0.2-1.20.1-Forge.jar
ImmediatelyFast-1.2.6+1.20.2.jar
industrial-foregoing-1.20.1-3.5.9.jar
infernalmobs-1.20.1.0.jar
InsaneLib-1.11.1-mc1.20.1.jar
inventorysorter-1.20.1-23.0.1.jar
invhud.forge.1.20.1-3.4.18.jar
ironchest-1.20.1-14.4.4.jar
ironfurnaces-1.20.1-4.1.3.jar
IronJetpacks-1.20.1-7.0.2.jar
item-filters-forge-2001.1.0-build.55.jar
Jade-1.20.1-forge-11.6.1.jar
JadeAddons-1.20.1-forge-5.2.0.jar
JAOPCA-1.20.1-4.4.5.7.jar
jei-1.20.1-forge-15.2.0.27.jar
justenoughbreeding-forge-1.20.x-1.0.7.jar
JustEnoughProfessions-forge-1.20.1-3.0.1.jar
JustEnoughResources-1.20.1-1.4.0.238.jar
Kambrik-6.1.1+1.20.1-forge.jar
Kc's+Growable+Ores-1.20.1-1.0.5.jar
Kiwi-1.20.1-forge-11.1.1.jar
kleeslabs-forge-1.20-15.0.0.jar
kotlinforforge-4.5.0-all.jar
KryptonReforged-0.2.3.jar
lemon_core-1.20.1-1.0.36.jar
lmft-1.0.3+1.20.1-forge.jar
Log-Begone-neoforge-1.20.1-1.0.9.jar
lootintegrations-1.20.1-3.3.jar
lootr-1.20-0.7.30.73.jar
lostcities-1.20-7.0.1.jar
lostsouls-1.20-4.0.0.jar
lost_aether_content-1.20.1-1.2.1.jar
MagnumTorch-v8.0.0-1.20.1-Forge.jar
mahoutsukai-1.20.1-v1.34.58.jar
MaxHealthFix-Forge-1.20.1-12.0.2.jar
mcjtylib-1.20-8.0.3.jar
megacells-forge-2.1.5-1.20.1.jar
merequester-forge-1.20.1-1.1.4.jar
MindfulDarkness-v8.0.2-1.20.1-Forge.jar
minecolonies-1.20.1-1.1.233-BETA.jar
mininggadgets-1.15.3.jar
mob_grinding_utils-1.20.1-1.0.3.jar
modernfix-forge-5.8.1+mc1.20.1.jar
mods.txt
moonlight-1.20-2.8.49-forge.jar
MouseTweaks-forge-mc1.20-2.25.jar
movingelevators-1.4.4-forge-mc1.20.1.jar
multipiston-1.20-1.2.31-ALPHA.jar
music_player-forge-1.20.1-2.7.0.236.jar
MysticalAgradditions-1.20.1-7.0.1.jar
MysticalAgriculture-1.20.1-7.0.4.jar
MysticalCustomization-1.20.1-5.0.0.jar
NaturesCompass-1.20.1-1.11.2-forge.jar
Necronomicon-Forge-1.0.2.jar
NetherChested-v8.0.1-1.20.1-Forge.jar
nethersdelight-1.20.1-4.0.jar
NoChatReports-FORGE-1.20.1-v2.2.2.jar
notenoughanimations-forge-1.6.4-mc1.20.jar
obscure_api-15.jar
obsidianui-0.1.2+1.20.1.jar
oceansdelight-1.0.2-1.20.jar
oculus-mc1.20.1-1.6.9.jar
open-parties-and-claims-forge-1.20.1-0.20.1.jar
origins-forge-1.20.1-1.10.0.2-all.jar
PackagedAuto-1.20.1-3.4.1.5.jar
Patchouli-1.20.1-81-FORGE.jar
Paxi-1.20-Forge-4.0.jar
Philips-Ruins1.20.1-2.4.jar
PickUpNotifier-v8.0.0-1.20.1-Forge.jar
pipez-1.20.1-1.2.0.jar
Placebo-1.20.1-8.3.7.jar
plane-1.20.1-1.0.6.jar
polymorph-forge-0.49.0+1.20.1.jar
Powah-5.0.2.jar
ProgressiveBosses-3.9.3-mc1.20.1.jar
PuzzlesLib-v8.0.24-1.20.1-Forge.jar
Raided-1.20.1-0.1.3.jar
rangedpumps-1.1.0.jar
rebornstorage-1.20.1-5.0.4.jar
recipeessentials-1.20.1-2.8.jar
refinedstorage-1.12.3.jar
refinedstorageaddons-0.10.0.jar
repurposed_structures-7.1.7+1.20.1-forge.jar
resourcefullib-forge-1.20.1-2.1.11.jar
ResourcePackOverrides-v8.0.1-1.20.1-Forge.jar
Rex's-AdditionalStructures-1.20.x-(v.4.2.1).jar
rftoolsbase-1.20-5.0.2.jar
right-click-harvest-3.2.3+1.20.1-forge.jar
RingsOfAscension-1.20.1-2.0.1.jar
RSInfinityBooster-1.20.1-1.0+32.jar
rsinsertexportupgrade-1.20.1-1.1.jar
rsrequestify-1.20.1-2.3.2.jar
rubidium-extra-0.5.2+mc1.20.1-build.104.jar
Ryoamiclights-0.1.3+1.20.1.jar
ScalableCatsForce-3.3.0-build-2-with-library.jar
scannable-MC1.20.1-forge-1.7.12+18ccb75.jar
Searchables-forge-1.20.1-1.0.2.jar
SereneSeasons-1.20.1-9.0.0.46.jar
ServerTabInfo-1.20-1.3.8.jar
ShieldExpansion-1.20.1-1.1.6a.jar
simpleshops-1.2.2.jar
SimpleStorageNetwork-1.20.1-1.10.0.jar
smarterfarmers-1.20-1.7.3.jar
snowundertrees-1.20.1-1.4.2.jar
solapplepie-1.20.1-2.3.0.jar
soundphysics-forge-1.20.1-1.2.1.jar
spark-1.10.53-forge.jar
Stackable+Potions-forge-1.20.1-1.0.0.jar
stackrefill-1.20.1-4.0.jar
stalwart-dungeons-1.20.1-1.2.8.jar
starlight-1.1.2+forge.1cda73c.jar
Stoneworks-v8.0.0-1.20.1-Forge.jar
storagedrawers-1.20.1-12.0.2.jar
Structory_1.20.2_v1.3.3.jar
Structory_Towers_1.20.2_v1.0.5.jar
structure_gel-1.20.1-2.14.0.jar
structurize-1.20.1-1.0.653-BETA.jar
suggestion-tweaker-1.20-1.5.1-forge.jar
supermartijn642configlib-1.1.8-forge-mc1.20.jar
supermartijn642corelib-1.1.15-forge-mc1.20.jar
TerraBlender-forge-1.20.1-3.0.0.169.jar
Terralith_1.20.2_v2.4.7.jar
textrues_embeddium_options-0.1.2+mc1.20.1.jar
the-conjurer-1.20.1-1.1.6.jar
themillmanlib-1.20.1-0.2.2.jar
The_Graveyard_3.0_(FORGE)_for_1.20.1.jar
The_Undergarden-1.20.1-0.8.8.jar
Tips-Forge-1.20.1-12.0.3.jar
titanium-1.20.1-3.8.22.jar
tlc_forge-1.0.3-R-1.20.X.jar
toofast-1.20-0.4.3.5.jar
ToughAsNails-1.20.1-9.0.0.96.jar
TradingPost-v8.0.1-1.20.1-Forge.jar
transparent-forge-8.0.1+1.20.1.jar
trashcans-1.0.18b-forge-mc1.20.jar
TravelersTitles-1.20-Forge-4.0.1.jar
twigs-1.20.1-3.1.0-forge.jar
twilightdelight-2.0.3.jar
twilightforest-1.20.1-4.3.1850-universal.jar
umbral_skies-1.3.jar
underground_jungle-2.0.1-forge-1.20.1.jar
universalgrid-1.20.1-1.0.jar
useful_backpacks-forge-1.20.1-2.0.1.122.jar
u_team_core-forge-1.20.1-5.1.4.269.jar
VendingMachine-1.20-1.0.10.jar
villagernames-1.20.1-5.2.jar
VillagersPlus_3.0_(FORGE)_for_1.20.1.jar
visuality-forge-2.0.2.jar
VisualWorkbench-v8.0.0-1.20.1-Forge.jar
Voidscape-1.20.1-1.3.230.jar
voidtotem-forge-1.20-3.0.1.jar
wandering+trader+trades.jar
watermedia-2.0.8.jar
waystones-forge-1.20-14.0.2.jar
wirelesschargers-1.0.9-forge-mc1.20.jar
worldedit-mod-7.2.15.jar
XaeroPlus-Forge-1.20.1-43-WM1.34.1-MM23.8.2.jar
XaerosWorldMap_1.34.1_Forge_1.20.jar
Xaeros_Minimap_23.8.2_Forge_1.20.jar
xnet-1.20-6.0.2.jar
xptome-1.20.1-2.1.8.jar
YungsApi-1.20-Forge-4.0.2.jar
YungsBetterDungeons-1.20-Forge-4.0.3.jar
YungsBetterEndIsland-1.20-Forge-2.0.4.jar
YungsBetterMineshafts-1.20-Forge-4.0.4.jar
YungsBetterNetherFortresses-1.20-Forge-2.0.5.jar
YungsBetterOceanMonuments-1.20-Forge-3.0.3.jar
YungsBetterStrongholds-1.20-Forge-4.0.3.jar
YungsBetterWitchHuts-1.20-Forge-3.0.3.jar
YungsBridges-1.20-Forge-4.0.3.jar
ZeroCore2-1.20.1-2.1.39.jar
[1.20.1] SecurityCraft v1.9.8.jar
 
 - Version 0.1.3
 - Branch 1.20.1

**Additional context**
I've attached logs below. When I tried loading / creating a world without RyoamicLights, everything works normally. Looks like maybe some incompatibility with Alex's Mobs? Unsure as to why tho. 

[crash-2023-10-16_11.52.21-client.txt](https://github.com/ThinkingStudios/LambDynamicLights-Forge/files/12919510/crash-2023-10-16_11.52.21-client.txt)

**Comment by TexBlock** [comment]
fixed in `0.1.4+1.20.1`

**Comment by TexBlock** [comment]
ars nouveau issue
