### ISSUE TITLE
Fabric version crashing game

### ISSUE THREAD

**Issue by zax71** [ThinkingStudios/RyoamicLights#42]
**Describe the bug**
Upon installing this mod in a Fabric environment, the game does not launch

**To Reproduce**
1. Install fabric 1.20 v0.16.2
2. Install RyoamicLights, ObsidianUI and Fabric API
3. Launch the game
4. Note that the game does not start and there is a crash log

**Expected behavior**
The game to not crash on launch

**Desktop (please complete the following information):**
 - OS: Debian Testing with AwesomeWM
 - Minecraft 1.20
 - Fabric Loader version 0.16.2
 - Mods Fabric API v0.102, ObsidianUI v0.2.7, Ryoamiclights v0.2.11
 - Version 0.2.11
 - Branch mc1.20

**Additional context**
https://mclo.gs/FTFtajN

**Comment by girshcatt** [comment]
try 0.2.9 version

**Comment by TexBlock** [comment]
Unable to reproduce, try deleting the old config.
