### ISSUE TITLE
Add support for Fabric Loader 0.16.0 and higher

### ISSUE THREAD

**Issue by zed1ker** [ThinkingStudios/RyoamicLights#43]
There may be a bug, but the mod does not run on fabric loader versions above 0.15.11 and above

**Comment by girshcatt** [comment]
https://github.com/ThinkingStudios/RyoamicLights/issues/40#issuecomment-2295410720
try 0.2.8

**Comment by girshcatt** [comment]
hmm 0.2.9 and 0.2.11 work perfectly on latest loader 0.16.2

**Comment by zed1ker** [comment]
Hmm, when I run the latest version 0.2.11, I get an error and the game does not start https://mclo.gs/WKF2XDy

**Comment by zed1ker** [comment]
0.2.8 not work
