### ISSUE TITLE
Quick little

### ISSUE THREAD

**Issue by ImpulsiveLass** [ThinkingStudios/RyoamicLights#5]
I'm playing forge 47.1.3, just asking if the mod works with it in the first place, holding a torch makes my shield brighter but doesn't effect the environment. I got 0.1.3-1.20.1 of ryodynamic, 0.1.2-1.20.1 of obsidianui, and 0.2.2-1.20.1 of embeddium.
![2023-10-20_02 46 34](https://github.com/ThinkingStudios/LambDynamicLights-Forge/assets/92990441/8b75a76b-60a9-42af-89d5-fa6f49ad672c)
![2023-10-20_02 46 35](https://github.com/ThinkingStudios/LambDynamicLights-Forge/assets/92990441/aa939941-2204-4b59-9592-97340b5b7ffb)

**Comment by ImpulsiveLass** [comment]
![2023-10-20_18 09 34](https://github.com/ThinkingStudios/LambDynamicLights-Forge/assets/92990441/939292dd-7873-4505-91cf-29b579c86dcf)
![2023-10-20_18 09 35](https://github.com/ThinkingStudios/LambDynamicLights-Forge/assets/92990441/8ebd7e7e-30a7-42bd-993c-8ed6a6604906)
Just another good photo of what I'm seeing, non solids appear lit while the blocks are unaffected.

**Comment by TexBlock** [comment]
fixed in `0.1.4+1.20.1`

**Comment by ImpulsiveLass** [comment]
Not for me, this is in that new build,

https://github.com/ThinkingStudios/LambDynamicLights-Forge/assets/92990441/67769897-bd14-4205-bbb9-8a8fd0bdc9c1

Maybe its a compatibility issue? I am creating a modpack atm

**Comment by ImpulsiveLass** [comment]
![Screenshot 2023-10-22 202458](https://github.com/ThinkingStudios/LambDynamicLights-Forge/assets/92990441/d6b52f63-a0c2-4a60-9c57-97b9330ee9f1)
Here is my pack's current modlist in case any incompatibility is known.

**Comment by ImpulsiveLass** [comment]
Can confirm the mod works perfectly when I moved to forge 47.1.76. It’s just a 47.1.3 issue
