### ISSUE TITLE
Custom luminance JSONs are not parsed

### ISSUE THREAD

**Issue by Alkaline-Dreams** [ThinkingStudios/RyoamicLights#8]
**Describe the bug**
[My Minecraft mod](https://github.com/VioletRoses/WeirdEquipmentRearchitected) uses LambDynamicLights for certain items, and though I've successfully hooked into the RyoamicLights API for entities, the mod appears not to parse item luminance JSONs, even though the folder structure is setup the exact same as on Fabric.

**To Reproduce**
1. Launch instance with [Weird Equipment](https://github.com/VioletRoses/WeirdEquipmentRearchitected/releases/tag/1.0.4) (1.0.4 or higher) and RyoamicLights
2. Equip Netherite Torch Pickaxe
3. Observe no lighting being emitted

**Screenshots**
Mod running with RyoamicLights:
![Screenshot 2023-11-07 130135](https://github.com/ThinkingStudios/LambDynamicLights-Forge/assets/35690943/9d8db0c6-c88b-4494-b664-7abd244e0067)

Running with LambDynamicLights:
![Screenshot 2023-11-07 130122](https://github.com/ThinkingStudios/LambDynamicLights-Forge/assets/35690943/fc11a9fe-bd3e-4ddd-860c-88b26f05e25e)

**Desktop (please complete the following information):**
 - OS: Windows
 - Minecraft 1.20.1
 - Fabric Loader version 0.14.24
 - Mods: Rubidium, RyoamicLights, WeirdEquipment
 - Version 0.1.5

**Comment by Alkaline-Dreams** [comment]
FYI i've tried renaming the "dynamiclights" folder in assets to "ryoamiclights" thinking that could've been the issue and it just wasn't documented in the API.md but that did nothing.

**Comment by TexBlock** [comment]
You seem to have misplaced Custom luminance JSON, it should be in `assets\<modid>\dynamiclights\`.

**Comment by TexBlock** [comment]
This is RyoamicLights' `ResourceReloader` issue, will fix in `0.1.6`
