### ISSUE TITLE
Dynamic lightning is buggy with modern fix with dynamic resources enabled

### ISSUE THREAD

**Issue by kakashi1464** [ThinkingStudios/RyoamicLights#9]
**Describe the bug**

Dynamic lightning is slow and don't luminance terrain properly with modern fix with dynamic resources enabled

**To Reproduce**
1. Install Ryoamic Lights with its dependencies and Modern Fix
2. Go to Modern Fix GUI
3. Enable dynamic resources
4. Restart minecraft
5. Enter the world
6. See what I described in the bug description

**Expected behavior**
The bug will be fixed and everything will look the same without enabling dynamic resources

**Screenshots**
![image](https://github.com/ThinkingStudios/LambDynamicLights-Forge/assets/126709049/bff9ad19-2896-43d6-bdc1-2c2278facd14)

**Desktop (please complete the following information):**
 - OS: [Windows 10]
 - Minecraft [1.20.1]
 - Forge [47.1.3]
 - Mods [Ryoamic lights, Architectury API, Modern Fix, Obsidian UI]
 - Version [0.1.5+1.20.1]
 - Branch [1.20-forge]

**Comment by TexBlock** [comment]
Does this problem still occur if you disable `dynamic resources` feature?

**Comment by kakashi1464** [comment]
![image](https://github.com/ThinkingStudios/LambDynamicLights-Forge/assets/126709049/d2b08f0a-171d-4af6-8a85-4868ddd3de7e)
This image shows the problem more clearly

**Comment by kakashi1464** [comment]
> Does this problem still occur if you disable `dynamic resources` feature?

no

**Comment by kakashi1464** [comment]
![image](https://github.com/ThinkingStudios/LambDynamicLights-Forge/assets/126709049/98dbc936-d601-41a0-a895-7a257592e07c)
enabling the Forge Lightning pipeline made it even worse

**Comment by kakashi1464** [comment]
Do you need latest log and debug log?

**Comment by TexBlock** [comment]
> Do you need latest log and debug log?

yes

**Comment by kakashi1464** [comment]
I’ll send it when I get home, that is, in 4.5 hours

**Comment by kakashi1464** [comment]
[latest.log](https://mclo.gs/lBiRDw5)
[debug.log](https://mclo.gs/uPfkMS5)

**Comment by TexBlock** [comment]
log not report any useful information.
maybe is Modern Fix (dynamic resources) incompatible with this mod? (But I still think it's my side of the problem)

**Comment by kakashi1464** [comment]
Btw as far as I remember, it happens with every dynamic light mod for me.

**Comment by kakashi1464** [comment]
issue seems to be fixed with newer version of Ryoamic lights and Modern fix

**Comment by kakashi1464** [comment]
Thanks for respond!

**Comment by kakashi1464** [comment]
Merry crysis!
